import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import FirstSec from "@/components/FirstSec";
import GetStarted from "@/components/GetStarted";
import SaveTime from "@/components/SaveTime";
import ViewPlan from "@/components/ViewPlan";
import Signup from "@/components/Signup";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SMB LEADS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
        <FirstSec />
        <GetStarted />
        <SaveTime />
        <ViewPlan />
        <Signup />
      </main>
    </>
  );
}
